const ActionTypes={
	ADD_SEARCH_FIELD:'ADD_SEARCH_FIELD',
	GLOBAL_LOADING:'GLOBAL_LOADING',
	ADD_GLOBAL_DATA:'ADD_GLOBAL_DATA',
	GLOBAL_DATA_FAILED:'GLOBAL_DATA_FAILED',
	ADD_GLOBAL_GRAPH_CONFIRMED_CASES:' ADD_GLOBAL_GRAPH_CONFIRMED_CASES',
	ADD_GLOBAL_GRAPH_DEATHS_CASES:' ADD_GLOBAL_GRAPH_DEATHS_CASES',
	GLOBAL_GRAPH_CONFIRMED_CASES_FAILED:'GLOBAL_GRAPH_CONFIRMED_CASES_FAILED',
	GLOBAL_GRAPH_DEATHS_CASES_FAILED:'GLOBAL_GRAPH_DEATHS_CASES_FAILED',
	COUNTRY_LOADING:'COUNTRY_LOADING',
	ADD_COUNTRY_DATA:'ADD_COUNTRY_DATA',
	COUNTRY_DATA_FAILED:'COUNTRY_DATA_FAILED',
	PROVINCE_STATE_LOADING:'PROVINCE_STATE_LOADING',
	ADD_PROVINCE_STATE:'ADD_PROVINCE_STATE',
	PROVINCE_STATE_FAILED:'PROVINCE_STATE_FAILED'
};

export default ActionTypes;